theme: jekyll-theme-minimal
title: James Harris's Repo
description: I'm just posting things here. Documenting my work in some computer science and posting designs. 
logo: https://github.com/jamesaharris/amesjarris.com/blob/main/Untitled%20drawing%20(17).png?raw=true
show_downloads: false
