theme: jekyll-theme-minimal
title: James Harris's Repo
description: I'm just posting things here. Documenting my work in some computer science and posting designs. 
logo: 'Untitled drawing (17).png'
show_downloads: false
