ardescription: Amesjarris.com
logo: 'https://github.com/jamesaharris/amesjarris.com/blob/Legacy/Untitled%20drawing%20(17).png?raw=true'
show_downloads: false
markdown: gfm
title: null
name: Home

theme: jekyll-theme-minimal
